import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/header";

import MuiThemeProvider from "@/theme";


const roboto = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MuiThemeProvider>
        <body className={roboto.className}>
          <Header />
          {children}
        </body>
      </MuiThemeProvider>
    </html>
  );
}
