import type { Metadata } from "next";
import { Goldman } from "next/font/google";

import ThemeProvider from "@/theme";
import AppLayout from "@/layouts/app-layout";

const goldman = Goldman({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-goldman",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={goldman.className}>
          <AppLayout>{children}</AppLayout>
        </body>
      </ThemeProvider>
    </html>
  );
}
